### ISSUE TITLE
Client Plugin

### ISSUE THREAD

**Issue by Basilakis** [aristath/edd-remote-installer#8]
Hey @aristath !

Hope you are fine.
I can not see the client - side plugin here, has it been removed?

**Comment by aristath** [comment]
client is in the includes folder. 
Though I don't have an active installation using EDD Software Licensing plugin anymore which is why this repository hasn't been updated in a year

**Comment by Basilakis** [comment]
If anything that does not work, will be happy to contribute. But your stuff always work even a long time after! :)

**Comment by aristath** [comment]
I hope it still does... 
If it doesn't then I'm sure a bit of tweaking will make it functional again. ;)
Any contributions are more than welcomed, and in fact I'm looking for a co-maintainer for this repository, so if it gets the job done and you want to be a part of it let me know 👍

**Comment by danieliser** [comment]
Let me know, already an EDD user, contrib & extension author. Happy to help take this over as we are rebuilding it now for our needs as well.

**Comment by aristath** [comment]
Hey guys, this repo needed a lot of work and since it was built a lot of things have changed in the EDD world so I decided to rebuild it from scratch.
This repository will be archived and you can find links to the new ones in the readme file.
The server plugin is now functional, the client-side is a work in progress but hopefully I'll have it ready this week as well 'cause I'll need it pretty soon as well 👍
